
---
apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: surkat-helloworld.workshop.dev.signicat.com.
  name: helloworld-service
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      name: http
      port: 8085
      targetPort: http
      nodePort: 31542

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: registry.gitlab.com/sysdev-tutorials/springboot/auth_demo:latest
          ports:
            - containerPort: 8085
              name: http
      imagePullSecrets:
        - name: gitlab


